import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ParentWrapper from "@/components/ParentWrapper";
import StyledComponentsRegistry from "./registry";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menuItems= [
  {
    title:'home',
    link:'/',
  },
  {
    title:'about',
    link:'/about',
  },
  {
    title:'productions',
    link:'/productions',
  },
  {
    title:'news',
    link:'/news',
  }
];
export default function RootLayout({ children, params, searchParams }) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StyledComponentsRegistry>
          
           <ParentWrapper menuItems={menuItems}>
            {children}
           </ParentWrapper>
        
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
